import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";

export default function ExplanationPanel({ projectId, open, onClose, preview }) {
  const query = useQuery({ queryKey: ["explanation", projectId], queryFn: () => api.explain(projectId), enabled: Boolean(open && projectId && !preview) });
  const data = preview ? { top_contributing_factors: preview.shap_factors, recommendations: preview.recommendations } : query.data;
  if (!open) return null;
  return <aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-lg"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Model explanation</p><h3 className="font-semibold text-slate-900">Risk drivers</h3></div>{onClose && <button onClick={onClose} className="text-slate-400 hover:text-slate-700">×</button>}</div>{query.isLoading && <div className="mt-5 space-y-3">{[1,2,3].map((x) => <div key={x} className="h-8 animate-pulse rounded bg-slate-100" />)}</div>}{query.isError && <p className="mt-4 text-sm text-red-600">Explanation unavailable. {query.error.message}</p>}{data && <><div className="mt-5 space-y-3">{data.top_contributing_factors.map((factor) => { const positive = factor.shap_value > 0; return <div key={factor.feature}><div className="flex justify-between text-xs"><span className="font-medium text-slate-700">{factor.feature.replaceAll("_", " ")}</span><span className={positive ? "text-red-600" : "text-emerald-600"}>{positive ? "Increases risk" : "Reduces risk"}</span></div><div className="mt-1 h-2 rounded bg-slate-100"><div className={`h-2 rounded ${positive ? "bg-red-500" : "bg-emerald-500"}`} style={{ width: `${Math.min(Math.abs(factor.shap_value) * 100, 100)}%` }} /></div></div> })}</div><div className="mt-5 rounded-lg bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">Recommendation</p><p className="mt-1 text-sm text-slate-700">{data.recommendations.join(". ")}</p></div></>}</aside>;
}
