import RiskBadge from "./RiskBadge";

const delayBand = (probability) => probability < .2 ? "0–3 mo" : probability < .4 ? "3–6 mo" : probability < .6 ? "6–12 mo" : probability < .8 ? "12–18 mo" : "18+ mo";

export default function ProjectTable({ projects, onSelect, sort, setSort }) {
  const ordered = [...projects].sort((a,b) => String(a[sort]).localeCompare(String(b[sort]), undefined, { numeric: true }));
  const head = (label, key) => <th onClick={() => setSort(key)} className="cursor-pointer px-4 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-400">{label}{sort === key ? " ↓" : ""}</th>;
  return <><div className="space-y-3 md:hidden">{ordered.map((project)=><button key={project.project_id} onClick={()=>onSelect(project)} className="gov-paper w-full rounded-lg p-4 text-left"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#0f766e]">{project.project_id}</p><p className="mt-1 font-semibold text-slate-900">{project.project_name}</p></div><RiskBadge category={project.risk_category}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><p className="text-slate-500">{project.project_type}</p><p className="text-right font-medium text-slate-700">{Math.round(project.delay_probability * 100)}% · {delayBand(project.delay_probability)}</p><p className="text-slate-500">{project.district}, {project.state}</p></div></button>)}</div><div className="gov-paper hidden overflow-x-auto rounded-lg md:block"><table className="w-full min-w-[760px]"><thead className="border-b border-[#d9d2c3] bg-[#f4efe4]"><tr>{head("Project", "project_name")}{head("Type", "project_type")}{head("State", "state")}<th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider text-slate-500">District</th>{head("Risk", "risk_category")}{head("Delay", "delay_probability")}</tr></thead><tbody>{ordered.map((project) => <tr key={project.project_id} onClick={() => onSelect(project)} className="cursor-pointer border-b border-[#eee8db] last:border-0 hover:bg-amber-50"><td className="px-4 py-4 font-semibold text-slate-800">{project.project_name}</td><td className="px-4 py-4 text-sm text-slate-600">{project.project_type}</td><td className="px-4 py-4 text-sm text-slate-600">{project.state}</td><td className="px-4 py-4 text-sm text-slate-600">{project.district}</td><td className="px-4 py-4"><RiskBadge category={project.risk_category} /></td><td className="px-4 py-4 text-sm font-semibold text-slate-700">{Math.round(project.delay_probability * 100)}% <span className="block text-xs font-normal text-slate-500">{delayBand(project.delay_probability)}</span></td></tr>)}</tbody></table></div></>;
}
