import { useState } from "react";
import { useLocation } from "react-router-dom";
import Plot from "react-plotly.js";
import { useQuery, useMutation } from "@tanstack/react-query";
import { api } from "../api/client";
import StatCard from "../components/StatCard";
import RiskBadge from "../components/RiskBadge";
import RiskMap from "../components/RiskMap";
import ExplanationPanel from "../components/ExplanationPanel";
import ProjectTable from "../components/ProjectTable";

const error = (query) => query.isError && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Data unavailable. {query.error.message}</div>;
const title = (eyebrow, heading, text) => <header className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{heading}</h1><p className="mt-2 text-slate-500">{text}</p></header>;

export function Dashboard() { const query = useQuery({ queryKey:["summary"], queryFn:api.summary }); const summary = query.data; const counts = Object.fromEntries((summary?.risk_category_counts || []).map((x) => [x.risk_category, x.count])); const states = summary?.average_delay_probability_by_state || []; return <>{title("National overview", "Land acquisition risk dashboard", "Live portfolio indicators and modeled delay exposure.")}{error(query)}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total projects" value={summary?.total_projects} loading={query.isLoading}/><StatCard label="High risk" value={counts.High || 0} tone="High" loading={query.isLoading}/><StatCard label="Medium risk" value={counts.Medium || 0} tone="Medium" loading={query.isLoading}/><StatCard label="Low risk" value={counts.Low || 0} tone="Low" loading={query.isLoading}/></div>{summary && <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-800">Average delay risk by state</h2><Plot data={[{ x:states.map(x=>x.state), y:states.map(x=>x.average_delay_probability*100), type:"bar", marker:{color:"#0f766e"}, hovertemplate:"%{x}: %{y:.1f}%<extra></extra>" }]} layout={{autosize:true,height:300,margin:{l:45,r:10,t:20,b:70},paper_bgcolor:"white",plot_bgcolor:"white",yaxis:{ticksuffix:"%",gridcolor:"#e2e8f0"},xaxis:{tickangle:-30}}} config={{displayModeBar:false}} className="w-full" /></section><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-800">Risk distribution</h2><Plot data={[{ values:[counts.Low||0,counts.Medium||0,counts.High||0], labels:["Low","Medium","High"], type:"pie", hole:.58, marker:{colors:["#059669","#d97706","#dc2626"]}, textinfo:"label+percent" }]} layout={{autosize:true,height:300,margin:{l:10,r:10,t:10,b:10},paper_bgcolor:"white",showlegend:false}} config={{displayModeBar:false}} className="w-full" /></section></div>}</>; }

function Detail({ project, onExplain }) { const prediction = useMutation({ mutationFn:() => api.predict(project.project_id) }); return <aside className="space-y-4 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{project.project_id}</p><h2 className="font-semibold text-slate-900">{project.project_name}</h2></div><RiskBadge category={project.risk_category}/></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-400">Location</dt><dd className="font-medium">{project.district}, {project.state}</dd></div><div><dt className="text-slate-400">Delay probability</dt><dd className="font-medium">{Math.round(project.delay_probability*100)}%</dd></div><div><dt className="text-slate-400">Compensation</dt><dd className="font-medium">{project.compensation_percentage}%</dd></div><div><dt className="text-slate-400">Disputes</dt><dd className="font-medium">{project.legal_disputes}</dd></div></dl><button onClick={onExplain} className="w-full rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">View explanation</button><button onClick={()=>prediction.mutate()} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700">{prediction.isPending ? "Predicting…" : "Predict"}</button>{prediction.data && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Predicted delay: {Math.round(prediction.data.delay_probability*100)}% · {prediction.data.risk_category} risk</p>}{prediction.isError && <p className="text-sm text-red-600">Prediction unavailable.</p>}</aside>; }

export function MapPage() { const location = useLocation(); const focusProject = location.state?.focusProject; const query = useQuery({ queryKey:["geo"], queryFn:api.geo }); const [project,setProject]=useState(focusProject || null); const [explain,setExplain]=useState(false); return <>{title("Geospatial view", "Project risk map", "Select a project marker to inspect acquisition status and ML risk factors.")}{error(query)}<div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="overflow-hidden rounded-xl bg-white p-2 shadow-sm ring-1 ring-slate-200">{query.isLoading ? <div className="h-[430px] animate-pulse rounded-lg bg-slate-100"/> : <RiskMap data={query.data} focusProject={focusProject} onSelect={(p)=>{setProject(p);setExplain(false)}}/>}</section><div className="space-y-4">{project ? <Detail project={project} onExplain={()=>setExplain(true)}/> : <div className="rounded-xl border border-dashed border-slate-300 p-7 text-sm text-slate-500">Select a risk marker to view project details.</div>}<ExplanationPanel projectId={project?.project_id} open={explain} onClose={()=>setExplain(false)}/></div></div></>; }

export function ProjectsPage() { const [filters,setFilters]=useState({state:"",district:"",risk_category:""}); const [offset,setOffset]=useState(0); const [sort,setSort]=useState("project_name"); const [selected,setSelected]=useState(null); const [explain,setExplain]=useState(false); const query=useQuery({queryKey:["projects",filters,offset],queryFn:()=>api.projects({...filters,offset,limit:10})}); const update=(key,value)=>{setFilters({...filters,[key]:value});setOffset(0)}; return <>{title("Portfolio register", "Acquisition projects", "Filter live records, open a project, then generate a fresh delay prediction.")}{error(query)}<div className="mb-5 grid gap-3 md:grid-cols-3">{[["state","State"],["district","District"],["risk_category","Risk category"]].map(([key,label])=><input key={key} aria-label={label} value={filters[key]} onChange={e=>update(key,e.target.value)} placeholder={`Filter by ${label.toLowerCase()}`} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-500"/>)}</div><div className="grid gap-6 xl:grid-cols-[1fr_340px]"><div>{query.isLoading?<div className="h-96 animate-pulse rounded-xl bg-slate-100"/>:<ProjectTable projects={query.data?.items||[]} onSelect={(p)=>{setSelected(p);setExplain(false)}} sort={sort} setSort={setSort}/>}<div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{query.data?.total || 0} projects</span><div className="flex gap-2"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-10))} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><button disabled={(query.data?.items.length||0)<10} onClick={()=>setOffset(offset+10)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div></div><div className="space-y-4">{selected && <Detail project={selected} onExplain={()=>setExplain(true)}/>}<ExplanationPanel projectId={selected?.project_id} open={explain} onClose={()=>setExplain(false)}/></div></div></>; }

export function AlertsPage() { const query=useQuery({queryKey:["alerts"],queryFn:api.alerts}); return <>{title("Operational signals", "Risk alerts", "Newest alerts first, with risk severity and delivery outcome.")}{error(query)}<div className="space-y-3">{query.isLoading&&[1,2,3].map(x=><div key={x} className="h-28 animate-pulse rounded-xl bg-slate-100"/>)}{query.data?.map((alert)=>{const level=alert.risk_score_at_trigger>60?"High":alert.risk_score_at_trigger>30?"Medium":"Low";return <article key={alert.id} className={`rounded-xl border-l-4 bg-white p-5 shadow-sm ${level==="High"?"border-red-500":level==="Medium"?"border-amber-500":"border-emerald-500"}`}><div className="flex justify-between gap-4"><div><p className="font-semibold text-slate-900">{alert.message}</p><p className="mt-2 text-sm text-slate-500">Project {alert.project_id} · {new Date(alert.created_at).toLocaleString()}</p></div><RiskBadge category={level}/></div><p className="mt-3 text-xs font-medium text-slate-500">Channel: {alert.channel} · Delivery: {alert.status}</p></article>})}{query.data?.length===0&&<p className="rounded-xl bg-white p-8 text-center text-slate-500 shadow-sm">No alerts recorded.</p>}</div></>; }
