import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";

const roles = [["ADMIN", "Admin"], ["LAND_ACQUISITION_AUTHORITY", "Land Acquisition Authority"], ["DISTRICT_ADMINISTRATION", "District Administration"], ["STATE_GOVERNMENT", "State Government"], ["PROJECT_IMPLEMENTING_AGENCY", "Project Implementing Agency"], ["POLICY_MAKER", "Policy Maker"]];
const blank = { official_name: "", organization: "", designation: "", email: "", employee_id: "", state: "", district: "", requested_role: "" };
export default function RegisterPage() {
  const [form, setForm] = useState(blank), [states, setStates] = useState([]), [districts, setDistricts] = useState([]), [document, setDocument] = useState(null), [result, setResult] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { api.locations().then((data) => setStates(data.states)).catch(() => setError("Location list unavailable.")); }, []);
  useEffect(() => { if (!form.state) return setDistricts([]); api.locations(form.state).then((data) => setDistricts(data.districts)).catch(() => setDistricts([])); }, [form.state]);
  const change = (event) => setForm((old) => ({ ...old, [event.target.name]: event.target.value }));
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); setResult(""); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); data.append("supporting_document", document); await api.register(data); setResult("Request submitted. Administrator approval required before sign in."); setForm(blank); setDocument(null); } catch (cause) { setError(cause.response?.data?.detail || "Could not submit request."); } finally { setBusy(false); } }
  const input = "mt-2 w-full rounded border border-slate-300 bg-white px-3 py-2.5";
  return <main className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><form onSubmit={submit} className="gov-paper p-6 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0f766e]">Account request</p><h1 className="mt-2 text-3xl font-bold text-[#102a43]">Request access</h1><p className="mt-3 text-sm leading-6 text-slate-600">Government email and authorization document required. Request stays pending until review.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["official_name","Official name"],["organization","Department / organization"],["designation","Designation"],["email","Official government email"],["employee_id","Employee / official ID"]].map(([name,label]) => <label key={name} className="block text-sm font-semibold text-slate-700">{label}<input name={name} required type={name === "email" ? "email" : "text"} value={form[name]} onChange={change} className={input} /></label>)}<label className="block text-sm font-semibold text-slate-700">State<select name="state" value={form.state} onChange={(event) => { change(event); setForm((old) => ({ ...old, district: "" })); }} className={input}><option value="">Select state</option>{states.map((state) => <option key={state}>{state}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">District<select name="district" value={form.district} onChange={change} className={input}><option value="">Select district</option>{districts.map((district) => <option key={district}>{district}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700 sm:col-span-2">Requested role<select required name="requested_role" value={form.requested_role} onChange={change} className={input}><option value="">Select role</option>{roles.map(([code,name]) => <option key={code} value={code}>{name}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700 sm:col-span-2">Authorization letter or ID proof<input required accept=".pdf,.png,.jpg,.jpeg" type="file" onChange={(event) => setDocument(event.target.files?.[0] || null)} className="mt-2 block w-full text-sm" /></label></div>{error && <p role="alert" className="mt-5 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}{result && <p className="mt-5 rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{result}</p>}<div className="mt-6 flex items-center gap-4"><button disabled={busy || !document} className="rounded bg-[#0f766e] px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit request"}</button><Link to="/login" className="font-semibold text-[#0f766e]">Back to sign in</Link></div></form></main>;
}
